name: Run Tests

on: [push]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'

      - name: Restore dependencies
        run: dotnet restore lab8

      - name: Build
        run: dotnet build --configuration Release lab8

      - name: Run Tests
        run: dotnet test --configuration Release --no-build lab8
